import React,{useEffect,useMemo,useRef,useState}from'react';import{createRoot}from'react-dom/client';import mermaid from'mermaid';import'./style.css';import'./operations.css';
const menus=['대시보드','자산 관리','Agent 운영'];
async function api(url,options={}){const r=await fetch(url,{...options,headers:{...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),...options.headers}});if(r.status===401)throw Object.assign(new Error('unauthorized'),{status:401});if(!r.ok)throw new Error((await r.text())||`HTTP ${r.status}`);return r.status===204?null:r.json()}
function Login({onLogin}){const[u,setU]=useState(''),[p,setP]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);setError('');try{onLogin(await api('/api/v1/auth/login',{method:'POST',body:JSON.stringify({username:u,password:p})}))}catch(e){setError(e.status===401?'아이디 또는 비밀번호를 확인하세요.':'서버에 연결할 수 없습니다.')}finally{setBusy(false)}}return <div className="login"><form onSubmit={submit}><div className="brand"><b>A</b> AssetFlow</div><h1>관리자 로그인</h1><p>IT 자산 정보는 인증된 관리자만 확인할 수 있습니다.</p><label>아이디<input autoFocus value={u} onChange={e=>setU(e.target.value)} required/></label><label>비밀번호<input type="password" value={p} onChange={e=>setP(e.target.value)} required/></label>{error&&<div className="loginerror">{error}</div>}<button disabled={busy}>{busy?'로그인 중…':'로그인'}</button></form></div>}
function Diagram({children}){const ref=useRef();useEffect(()=>{mermaid.initialize({startOnLoad:false,theme:'base',securityLevel:'strict',themeVariables:{primaryColor:'#eef0ff',primaryTextColor:'#182033',primaryBorderColor:'#5368e8',lineColor:'#718096',secondaryColor:'#e9f8f3',tertiaryColor:'#fff'}});mermaid.render('flow-'+Math.random().toString(36).slice(2),children).then(({svg})=>{if(ref.current)ref.current.innerHTML=svg})},[children]);return <div className="diagram" ref={ref}/>}
function ReleaseList(){const[rows,setRows]=useState([]),[error,setError]=useState('');async function load(){try{setRows(await api('/api/v1/admin/agent-releases'));setError('')}catch(e){setError(e.message)}}useEffect(()=>{load();window.addEventListener('agent-release-updated',load);return()=>window.removeEventListener('agent-release-updated',load)},[]);return <div className="releaselist"><h3>등록된 Agent 버전</h3>{error?<p className="result">목록 조회 실패: {error}</p>:<table className="settings"><thead><tr><th>버전</th><th>파일</th><th>크기</th><th>등록 시각</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.version}><td><b>v{r.version}</b></td><td>{r.filename}</td><td>{(Number(r.size_bytes)/1024/1024).toFixed(1)} MB</td><td>{new Date(r.created_at).toLocaleString('ko-KR')}</td></tr>):<tr><td colSpan="4">등록된 버전이 없습니다.</td></tr>}</tbody></table>}</div>}
function AgentOps(){const[token,setToken]=useState(''),[version,setVersion]=useState(''),[file,setFile]=useState(),[message,setMessage]=useState('');async function upload(e){e.preventDefault();const body=new FormData();body.append('version',version);body.append('file',file);setMessage('업로드 중…');try{const x=await api('/api/v1/admin/agent-releases',{method:'POST',headers:{'X-Update-Token':token},body});setMessage(`등록 완료: v${x.version} / SHA-256 ${x.sha256}`);window.dispatchEvent(new Event('agent-release-updated'))}catch(e){setMessage(`등록 실패: ${e.message}`)}}return <section><div className="intro"><div><h2>Agent 운영 흐름</h2><p>자료 수집, 파일 로그, 버전 배포와 자동 업데이트 구조를 확인합니다.</p></div></div><article className="panel ops"><h3>자동 업데이트 흐름</h3><Diagram>{`flowchart LR
A[관리자 EXE 등록] --> B[서버 SHA-256 계산·보관]
B --> C[Agent 5분 주기 최신 버전 조회]
C --> D{신규 버전?}
D -- 아니오 --> C
D -- 예 --> E[Bearer 인증 다운로드]
E --> F{SHA-256 일치?}
F -- 아니오 --> G[파일 폐기·오류 로그]
F -- 예 --> H[서비스 중지]
H --> I[기존 EXE 백업·신규 EXE 교체]
I --> J[서비스 재시작]`}</Diagram></article><div className="opsgrid"><article className="panel ops"><h3>자료 수집 및 전송</h3><Diagram>{`flowchart TD
T[기본 60분 주기] --> H[하드웨어·OS]
T --> N[IP·MAC·디스크]
T --> S[설치 소프트웨어 최대 2000건]
T --> P[BitLocker·Firewall·Defender]
H & N & S & P --> API[Inventory API 전송]
API --> DB[(PostgreSQL)]`}</Diagram></article><article className="panel"><h3>주기 및 저장 위치</h3><table className="settings"><tbody><tr><th>인벤토리 수집</th><td>CollectionMinutes</td><td>기본 60분 / 최소 5분</td></tr><tr><th>업데이트 확인</th><td>UpdateCheckMinutes</td><td>기본 5분 / 최소 5분</td></tr><tr><th>Agent 설정</th><td colSpan="2">%ProgramData%\AssetFlow\agent.json</td></tr><tr><th>실행 로그</th><td colSpan="2">설치폴더\logs\agent-YYYYMMDD.log</td></tr><tr><th>실행파일</th><td colSpan="2">%ProgramFiles%\AssetFlow\Agent</td></tr></tbody></table></article></div><article className="panel release"><h3>신규 Agent 실행파일 등록</h3><form onSubmit={upload}><input type="password" placeholder="업데이트 등록 토큰" value={token} onChange={e=>setToken(e.target.value)} required/><input placeholder="버전 (예: 0.3.0)" pattern="[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?" value={version} onChange={e=>setVersion(e.target.value)} required/><input type="file" accept=".exe" onChange={e=>setFile(e.target.files[0])} required/><button>버전 등록</button></form>{message&&<p className="result">{message}</p>}<ReleaseList/></article></section>}
function AssetTable({rows,loading}){return <div className="tablewrap"><table><thead><tr><th>장비명</th><th>사용자 / 부서</th><th>운영체제</th><th>IP 주소</th><th>마지막 접속</th><th>상태</th></tr></thead><tbody>{loading?<tr><td colSpan="6">불러오는 중…</td></tr>:!rows.length?<tr><td colSpan="6" className="none">등록된 자산이 없습니다.</td></tr>:rows.map(a=><tr key={a.id}><td><b>{a.hostname}</b><small>{a.serial_no||'-'}</small></td><td>{a.username||'-'} / {a.department||'미지정'}</td><td>{a.os_name||'-'} {a.os_version||''}</td><td>{a.ip_address||'-'}</td><td>{new Date(a.last_seen_at).toLocaleString('ko-KR')}</td><td><em className={a.online?'online':'offline'}>● {a.online?'온라인':'오프라인'}</em></td></tr>)}</tbody></table></div>}
function App(){const[user,setUser]=useState(undefined),[active,setActive]=useState('대시보드'),[q,setQ]=useState(''),[loading,setLoading]=useState(false),[assets,setAssets]=useState([]),[stats,setStats]=useState({total:0,online:0,offline:0,stale:0,security:{bitlocker:0,antivirus:0}});useEffect(()=>{api('/api/v1/auth/me').then(setUser).catch(()=>setUser(null))},[]);async function load(){setLoading(true);try{const[s,a]=await Promise.all([api('/api/v1/dashboard'),api('/api/v1/assets')]);setStats(s);setAssets(a)}catch(e){if(e.status===401)setUser(null)}finally{setLoading(false)}}useEffect(()=>{if(user)load()},[user]);const filtered=useMemo(()=>assets.filter(a=>JSON.stringify(a).toLowerCase().includes(q.toLowerCase())),[assets,q]);if(user===undefined)return <div className="splash">AssetFlow</div>;if(!user)return <Login onLogin={setUser}/>;async function logout(){await api('/api/v1/auth/logout',{method:'POST'});setUser(null)}return <><aside><div className="brand"><b>A</b> AssetFlow</div><nav>{menus.map(n=><button key={n} className={active===n?'on':''} onClick={()=>setActive(n)}><span>{n==='대시보드'?'⌂':'▣'}</span>{n}</button>)}</nav><div className="profile"><i>{user.username[0].toUpperCase()}</i><div><b>{user.username}</b><small>시스템 관리자</small></div><button onClick={logout}>로그아웃</button></div></aside><main><header><div><small>IT ASSET MANAGEMENT</small><h1>{active}</h1></div>{active!=='Agent 운영'&&<input value={q} onChange={e=>setQ(e.target.value)} placeholder="자산, 사용자 검색"/>}</header>{active==='Agent 운영'?<AgentOps/>:active==='자산 관리'?<section><div className="intro"><div><h2>자산 목록</h2><p>장비를 검색하고 상태를 확인하세요.</p></div></div><article className="panel table"><AssetTable rows={filtered} loading={loading}/></article></section>:<Dashboard stats={stats} rows={filtered.slice(0,6)} loading={loading} load={load} all={()=>setActive('자산 관리')}/>}</main></>}
function Dashboard({stats,rows,loading,load,all}){return <><section><div className="intro"><div><h2>자산 현황</h2><p>전체 IT 자산의 상태를 확인하세요.</p></div><button onClick={load}>↻ 새로고침</button></div><div className="stats"><Stat label="전체 PC" value={stats.total}/><Stat label="온라인" value={stats.online}/><Stat label="오프라인" value={stats.offline}/><Stat label="장기 미접속" value={stats.stale}/></div></section><section className="panel table"><div className="title"><div><h3>최근 접속 자산</h3><p>에이전트가 최근 보고한 장비입니다.</p></div><button onClick={all}>전체 보기 →</button></div><AssetTable rows={rows} loading={loading}/></section></>}function Stat({label,value}){return <article><span>{label}</span><strong>{value}</strong><small>Agent 보고 기준</small></article>}createRoot(document.getElementById('root')).render(<App/>);
